# Generated by Django 3.2.4 on 2021-09-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='goal_carbs',
            field=models.IntegerField(default='50', verbose_name='Węglowodany'),
        ),
        migrations.AddField(
            model_name='profile',
            name='goal_fat',
            field=models.IntegerField(default='75', verbose_name='Tłuszcz'),
        ),
        migrations.AddField(
            model_name='profile',
            name='goal_protein',
            field=models.IntegerField(default='100', verbose_name='Proteiny'),
        ),
        migrations.AddField(
            model_name='profile',
            name='goal_total_calories',
            field=models.IntegerField(default='3000', verbose_name='Kalorie'),
        ),
    ]
