# Generated by Django 3.2.4 on 2021-09-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210917_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='goal_carbs',
            field=models.IntegerField(default='50', verbose_name='Węglowodany-Cel'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='goal_fat',
            field=models.IntegerField(default='75', verbose_name='Tłuszcz-Cel'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='goal_protein',
            field=models.IntegerField(default='100', verbose_name='Proteiny-Cel'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='goal_total_calories',
            field=models.IntegerField(default='3000', verbose_name='Kalorie-Cel'),
        ),
    ]
