# Generated by Django 3.2.4 on 2021-08-02 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_customer_userfooditem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfooditem',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='userfooditem',
            name='fooditem',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='UserFooditem',
        ),
    ]
