# Generated by Django 3.2.4 on 2021-08-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210802_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jedzenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('total_calories', models.IntegerField()),
                ('fat', models.IntegerField()),
                ('protein', models.IntegerField()),
                ('carbs', models.IntegerField()),
                ('category', models.CharField(choices=[('S', 'Sniadanie'), ('S_II', 'Sniadanie II'), ('L', 'Lunch'), ('O', 'Obiad'), ('C', 'Przekąska'), ('K', 'Kolacja'), ('T', 'Trening'), ('W', 'Woda')], max_length=4)),
                ('date_eaten', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Fooditem',
        ),
        migrations.DeleteModel(
            name='Kategorie',
        ),
    ]
