# Generated by Django 3.2.4 on 2021-08-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20210804_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategorie',
            name='category',
            field=models.CharField(choices=[('S', 'Sniadanie'), ('S_II', 'Sniadanie II'), ('L', 'Lunch'), ('O', 'Obiad'), ('C', 'Przekąska'), ('K', 'Kolacja'), ('T', 'Trening'), ('W', 'Woda')], default='Sniadanie', max_length=4),
        ),
    ]
