# Generated by Django 3.2.4 on 2021-08-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_kategorie_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kategorie',
        ),
        migrations.AddField(
            model_name='jedzenie',
            name='category',
            field=models.CharField(choices=[('S', 'Sniadanie'), ('S_II', 'Sniadanie II'), ('L', 'Lunch'), ('O', 'Obiad'), ('C', 'Przekąska'), ('K', 'Kolacja'), ('T', 'Trening'), ('W', 'Woda')], default='Sniadanie', max_length=4),
        ),
    ]
