# Generated by Django 3.2.4 on 2021-08-05 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0009_auto_20210805_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('calorie', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['calorie'],
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='all_food_selected_today',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='food_selected',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='person_of',
        ),
        migrations.DeleteModel(
            name='PostFood',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
