# Generated by Django 3.2.4 on 2021-08-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20210805_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jedzenie',
            name='date_eaten',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
