# Generated by Django 3.2.4 on 2021-08-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_jedzenie_date_eaten'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jedzenie',
            name='date_eaten',
            field=models.DateField(auto_now_add=True),
        ),
    ]
